CREATE DATABASE store;

---create tables---
CREATE TABLE User(
   USER_ID		INT GENERATED ALWAYS AS IDENTITY,
   USERNAME		TEXT     NOT NULL,
   EMAIL		INT      NOT NULL,
   PASSWORD     CHAR(50) NOT NULL,
   ADDRESS      TEXT NOT NULL,
   CITY			CHAR(50) NOT NULL,
   STATE		CHAR(50) NOT NULL,
   PRIMARY KEY(USER_ID)

);

CREATE TABLE Product_Category(
  PRO_CAT_ID	INT GENERATED ALWAYS AS IDENTITY,
  CATEGORY_ID	INT	NOT NULL
  PRIMARY KEY(PRO_CAT_ID)
);

CREATE TABLE Product(
  PRODUCT_ID	INT	GENERATED ALWAYS AS IDENTITY,
  PRODUCT_NAME	CHAR(100)NOT NULL,
  PRODUCT_DESC	TEXT	 NOT NULL,
  PRO_CAT_ID	INT	NOT NULL,
  AVAILABILITY  CHAR(10)NOT NULL,
  PRODUCT_COST  NUMERIC,
  PRIMARY KEY(PRODUCT_ID),
  CONSTRAINT fk_product_category FOREIGN KEY(PRO_CAT_ID) REFERENCES Product_Category(PRO_CAT_ID)
);

CREATE TABLE Review(
  USER_ID			INT	NOT NULL,
  PRODUCT_ID		INT	NOT NULL,
  REVIEW_CONTENT 	TEXT,
  CONSTRAINT fk_user FOREIGN KEY(USER_ID) REFERENCES User(USER_ID),
  CONSTRAINT fk_product FOREIGN KEY(PRODUCT_ID) REFERENCES Product(PRODUCT_ID)
);

CREATE TABLE Rating(
  USER_ID		INT	NOT NULL,
  PRODUCT_ID 	INT	NOT NULL,
  RATING 		INT,
  CONSTRAINT fk_user FOREIGN KEY(USER_ID) REFERENCES User(USER_ID),
  CONSTRAINT fk_product FOREIGN KEY(PRODUCT_ID) REFERENCES Product_Category(PRODUCT_ID)
);

CREATE TABLE User_Order(
  ORDER_ID			INT GENERATED ALWAYS AS IDENTITY,
  ORDER_DATETIME	VARCHAR(255)	NOT NULL,
  DATE_CREATED		VARCHAR(255)	NOT NULL,
  USER_ID			INT	NOT NULL,
  PRIMARY KEY(ORDER_ID),
  CONSTRAINT fk_user FOREIGN KEY(USER_ID) REFERENCES User(USER_ID),
 
);

CREATE TABLE Sub_Order(
	SUB_ORDER_ID	INT	GENERATED ALWAYS AS IDENTITY,
	PRODUCT_ID		INT	NOT NULL,
	QUANTITY		INT	NOT NULL,
	ORDER_ID		INT	NOT NULL,
	COST			NUMERIC NOT NULL,
	PRIMARY KEY(SUB_ORDER_ID),
	CONSTRAINT fk_user_order FOREIGN KEY(ORDER_ID) REFERENCES User_Order(ORDER_ID),
	CONSTRAINT fk_product FOREIGN KEY(PRODUCT_ID) REFERENCES Product(PRODUCT_ID)
	);

CREATE TABLE Order_Payment(
	ORDER_PAYMENT_ID	INT GENERATED ALWAYS AS IDENTITY,
	ORDER_ID			INT	NOT NULL,
	COST				NUMERIC	NOT NULL,
	PAYMENT_STATUS		VARCHAR(255)	NOT NULL,
	PRIMARY KEY(ORDER_PAYMENT_ID),
	CONSTRAINT fk_user_order FOREIGN KEY(ORDER_ID) REFERENCES User_Order(ORDER_ID)
	
	);

CREATE TABLE Order_Address(
	ORDER_ADDRESS_ID	INT	GENERATED ALWAYS AS IDENTITY,
	ORDER_ID			INT	NOT NULL,
	ADDRESS				VARCHAR(255)	NOT NULL,
	PRIMARY KEY(ORDER_ADDRESS_ID),
	CONSTRAINT fk_user_order FOREIGN KEY(ORDER_ID) REFERENCES User_Order(ORDER_ID)
	);
	


  
  